name: Build and Release Desktop App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore NetworkChangerApp/NetworkChangerApp.csproj

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: |
        dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true
        app_version=$(dotnet exec --list-sdks | head -n 1 | awk '{print $1}')
        app_name="NetworkChangerApp"
        mkdir -p artifacts
        cp -r bin/Release/net6.0-windows/win-x64/publish ./artifacts/$app_name-$app_version

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: artifacts

  release:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: app
        path: artifacts

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Release of the application
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/*.zip
        asset_name: NetworkChangerApp-${{ github.ref }}.zip
        asset_content_type: application/zip
